zEntregas anteriores/E1_potatoes/config/routes.rb
Rails.application.routes.draw do
  resources :potatos

  root 'potatos#index'

end

zEntregas anteriores/E1_potatoes/app/models/potato.rb
class Potato < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 4 }
  validates :description, presence: true, length: { minimum: 10}
  validates :link, presence: true, length: { minimum: 10}
end

zEntregas anteriores/E1_potatoes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

zEntregas anteriores/E1_potatoes/app/controllers/potatos_controller.rb
class PotatosController < ApplicationController

  def index
    @potatos = Potato.all
  end

  def show
    @potato = Potato.find(params[:id])
  end

  def new
    @potato = Potato.new
  end
  
  def edit
    @potato = Potato.find(params[:id])
  end

  def create
    @potato = Potato.new(potato_params)

    if @potato.save
      redirect_to @potato
    else
      render "new"
    end
  end

  def update
    @potato = Potato.find(params[:id])

    if @potato.update(potato_params)
      redirect_to @potato
    else
      render "new"
    end
  end

  def destroy
    @potato = Potato.find(params[:id])

    @potato.destroy
    redirect_to potatos_path
  end

  private
    def potato_params
      params.require(:potato).permit(:name, :description, :link)
    end

end

zEntregas anteriores/E1_potatoes/app/helpers/application_helper.rb
module ApplicationHelper
end

zEntregas anteriores/E1_potatoes/app/helpers/potatos_helper.rb
module PotatosHelper
end

zEntregas anteriores/E1_potatoes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Potatos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

zEntregas anteriores/E1_potatoes/app/views/potatos/_form.html.erb
<%= form_for @potato do |potato| %>

  <% if @potato.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@potato.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @potato.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= potato.label :name %><br>
    <%= potato.text_field :name %>
  </p>

  <p>
    <%= potato.label :description %><br>
    <%= potato.text_area :description %>
  </p>

  <p>
    <%= potato.label :link %><br>
    <%= potato.text_field :link %>
  </p>

  <p>
    <%= potato.submit %>
  </p>

<% end %>

zEntregas anteriores/E1_potatoes/app/views/potatos/edit.html.erb
<h1>Edit potato</h1>

<%= render 'form' %>

<%= link_to 'Back', potatos_path %>

zEntregas anteriores/E1_potatoes/app/views/potatos/index.html.erb
<h1>Listing Potatos</h1>
<%= link_to 'New potato', new_potato_path %>
<br>
<br>
<table>
  <tr>
    <th> Name </th>
    <th> Description </th>
    <th> Image Link </th>
  </tr>

  <% @potatos.each do |potato| %>
    <tr>
      <td><%= potato.name %></td>
      <td><%= potato.description %></td>
      <td><%= link_to potato.link, potato.link %></td>
      <td><%= image_tag(potato.link) %></td>
      <td><%= link_to 'Show', potato_path(potato) %></td>
      <td><%= link_to 'Edit', edit_potato_path(potato) %></td>
      <td>
        <%= link_to 'Destroy', potato_path(potato),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

zEntregas anteriores/E1_potatoes/app/views/potatos/new.html.erb
<h1>New potato</h1>

<%= render 'form' %>

<%= link_to 'Back', potatos_path %>

zEntregas anteriores/E1_potatoes/app/views/potatos/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @potato.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @potato.description %>
</p>

<p>
  <strong>Image Link:</strong>
  <%= link_to @potato.link, @potato.link %>

</p>
<p>
  <strong>Image:</strong>
  <img src="<%=@potato.link%>">
</p>

<%= link_to 'Edit', edit_potato_path(@potato) %> |
<%= link_to 'Back', potatos_path %>