config/routes.rb
Rails.application.routes.draw do
# Root
  root 'store#index'

# Store
  get 'store/index'
  get 'store/product/:id', to: 'store#product', as: 'store_product'
  # get 'store/computers'
  # get 'store/deodorants'
  get 'store/products'

# Login
  get 'login', to: "login#ask"
  post 'login/validate'
  delete 'login/logout'

# Profile routes
  get 'profile', to: "profile#show"
  get 'profile/edit_password', to: "profile#edit_password"
  get 'profile/edit', to: "profile#edit"
  resources :profile, only: [:update]

# Admin routes
  get 'admin', to: 'admin#index'
  namespace :admin do
    # User management
    patch 'active_toggle', to: 'users#active_toggle'
    get 'users/:id/edit_password', to: 'users#edit_password', as: 'edit_user_password'
    resources :users

    # Product management
    resources :products
  end

# API
namespace :api do
    namespace :v1 do
        get '/', to: 'base#index'
        resources :products, only: [:index, :show, :update, :destroy]
    end
end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username,  presence: true
  validates :password,  presence: true, :on => :create
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  def self.login(username, password)
    user = User.find_by_username(username).try(:authenticate, password)
    if username.blank?
      return nil, "Debes ingresar un usuario"
    elsif user.nil? || !user
      return nil, "Usuario o clave incorrecto"
    elsif !user.active
      return nil, "Cuenta desactivada, contacta al admin"
    else
      return user, nil
    end
  end

  def active_toggle
    self.update(active: !self.active)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, except: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @hide_password = true
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def edit_password
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'El usuario fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'El usuario fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'El usuario fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  def active_toggle
    @user.active_toggle
    redirect_to params[:path]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :email, :admin, :active)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_admin_required
  before_action :set_user, except: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @hide_password = true
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'El usuario fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'El usuario fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'El usuario fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  def active_toggle
    @user.active_toggle
    redirect_to params[:path]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :email, :admin, :active)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "errores") %> impidieron guardar este usuario:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %></br>
    <%= f.text_field :username %>
  </div>
  <% unless hide_password %>
    <div class="field">
      <%= f.label :password %></br>
      <%= f.text_field :password %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %></br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
  <%= f.check_box :admin %>
  <%= f.label :admin %>
  </div>
  <div class="field">
  <%= f.check_box :active, { checked: true } %>
  <%= f.label :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Email</th>
      <th>Admin</th>
      <th>Activo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.admin ? "Si" : "No" %></td>
        <td><%= user.active ? "Si" : "No "%></td>
        <td><%= link_to 'Mostrar', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Eliminar', user, method: :delete, data: { confirm: "Se require confirmación para eliminar al usuario\n\t#{user.username}\n¿Estás seguro?" } %></td>
        <td><%=
        text = ""
        if user.active
          text = "Bloquear"
        else
          text = "Desbloquear"
        end
        link_to text, admin_active_toggle_path({id: user.id, path: users_path}), method: :patch
        %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo usuario', new_user_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Administrador:</strong>
  <%= @user.admin ? "Si" : "No" %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @user.active ? "Si" : "No" %>
</p>

<%=
text = ""
if @user.active
  text = "Bloquear"
else
  text = "Desbloquear"
end
link_to text, admin_active_toggle_path({id: @user.id, path: user_path}), method: :patch
%> |
<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Atrás', users_path %>

app/views/users/userAsk.html.erb
<div id="name_ask">
  <h1>Bienvenido</h1>
  <p>Para continuar por favor tu usuario y clave</p>
  <% if @error.present? %>
    <div class="error-message"><strong>Atención: </strong><%= @error %></div>
  <% end %>
  <%= form_tag user_userRemember_path do %>
    <div class="form-control">
      <%= label_tag(:username, 'Usuario') %>
      <%= text_field_tag(:username, nil, placeholder: "Ask Ketchup") %>
    </div>
    <div class="form-control">
      <%= label_tag(:pass, 'Clave') %>
      <%= password_field_tag(:pass) %>
    </div>
    <div class="form-control">
      <%= submit_tag("Ingresar") %>
    </div>
  <% end %>
</div>