config/routes.rb
Rails.application.routes.draw do
# Root
  root 'store#index'

# Store
  get 'store/index'
  get 'store/product/:id', to: 'store#product', as: 'store_product'
  # get 'store/computers'
  # get 'store/deodorants'
  get 'store/products'

# Login
  get 'login', to: "login#ask"
  post 'login/validate'
  delete 'login/logout'

# Profile routes
  get 'profile', to: "profile#show"
  get 'profile/edit_password', to: "profile#edit_password"
  get 'profile/edit', to: "profile#edit"
  resources :profile, only: [:update]

# Admin routes
  get 'admin', to: 'admin#index'
  namespace :admin do
    # User management
    patch 'active_toggle', to: 'users#active_toggle'
    get 'users/:id/edit_password', to: 'users#edit_password', as: 'edit_user_password'
    resources :users

    # Product management
    resources :products
  end

# API
namespace :api do
    namespace :v1 do
        get '/', to: 'base#index'
        resources :products, only: [:index, :show, :update, :destroy]
    end
end

end

app/views/layouts/_base_layout.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Nidastore</title>
        <%= stylesheet_link_tag 'application', media: 'all' %>
        <%= stylesheet_link_tag 'store', media: 'all' %>
        <%= javascript_include_tag 'application' %>
        <%= csrf_meta_tags %>
    </head>
    <body>

    <%= render "layouts/modal_view" %>

app/views/layouts/_main_nav_bar.html.erb
<header>

<nav class="principal_options">
<%=
  if @current_user != nil
    link_to "Mi Perfil", profile_path
  end
%>
<%=
  if @current_user != nil && @current_user.admin
    link_to "Administrar sitio", admin_path
  end
%>
<%=
  if @current_user != nil
    link_to "Cerrar sesion", login_logout_path, method: :delete
  else
    link_to "Iniciar sesion", login_path
  end
%>
</nav>

<nav class="company">
  <%= link_to image_tag('logo.png', height: '100', width:'100'), root_path %>
</nav>

app/views/layouts/_modal_view.html.erb
  <div id="bgwindow">
    <div id="window">
      <p class="cerrar">Cerrar</p>
      <p id="titulosss">
        Producto
      </p>
      <div class="imagen ">
      <img id="imagen_zoom"  src="" alt="" />
      </div>
      <p id="informacion">
        Descripcion
      </p>
      <nav>
        <a id="go_product" href="#">Ir al producto</a> |
        <a href="#">Agregar al carro</a>
      </nav>
    </div>
  </div>
  <div id="bgwindow_detalles">
    <div id="window">
      <p class="cerrar">Cerrar</p>
      <div id="more_options">
        Acá va las opciones
      </div>
      <br>
      <div id="more_options_pc">
          Colores: <br> -Rojo <br> -Azul <br> -Blanco
      </div>
      <br>
      <div id="more_options_des">
        Olores: <br> -Amargo <br> -Ácido <br> -Cítrico
      </div>
    </div>
  </div>

app/views/layouts/admin.html.erb
<%= render 'layouts/base_layout' %>
<%= render 'layouts/main_nav_bar' %>

<nav class="MenuCat">
    <%= link_to "Administrar usuarios", admin_users_path %>
    <%= link_to "Administrar productos", admin_products_path %>
</nav>

</header>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<%= render 'layouts/base_layout' %>
<%= render 'layouts/main_nav_bar' %>

</header>

<%= yield %>


</body>
</html>

app/views/layouts/store.html.erb
<%= render 'layouts/base_layout' %>
<%= render 'layouts/main_nav_bar' %>

<nav class="MenuCat">
    <%= link_to 'Inicio', store_products_path(family: 0, page: 0), remote: true %>
    <%= link_to 'Computadores', store_products_path(family: 1, page: 0), remote: true %>
    <%= link_to 'Desodorantes', store_products_path(family: 2, page: 0), remote: true %>
</nav>

</header>

<%= yield %>

</body>
</html>